# Generated by Django 3.2.7 on 2021-09-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_auto_20210926_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_person',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='sits',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
